#!/usr/bin/env python
"""
WordAPI.py
Copyright 2014 Wordnik, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os

from .models import *


class SubscriptionApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    

    def getSubscriptionsByCloudlet(self, cloudletId, **kwargs):
        """List All Subscriptions

        Args:
            cloudletId, str: The Cloudlet Id for the User (required)

            

        Returns: str
        """

        allParams = ['cloudletId']

        params = locals()
        for (key, val) in params['kwargs'].items():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getSubscriptionsByCloudlet" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/subscription/{cloudletId}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        if ('cloudletId' in params):
            replacement = str(self.apiClient.toPathValue(params['cloudletId']))
            resourcePath = resourcePath.replace('{' + 'cloudletId' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'str')
        return responseObject
        

        

    def addSubscription(self, body, cloudletId, **kwargs):
        """Add Subscriptions

        Args:
            body, SubsBlock:  (required)

            cloudletId, str: The Cloudlet Id for the User (required)

            

        Returns: str
        """

        allParams = ['body', 'cloudletId']

        params = locals()
        for (key, val) in params['kwargs'].items():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method addSubscription" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/subscription/{cloudletId}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}

        if ('cloudletId' in params):
            replacement = str(self.apiClient.toPathValue(params['cloudletId']))
            resourcePath = resourcePath.replace('{' + 'cloudletId' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'str')
        return responseObject
        

        

    def getSubscriptionsByCloudletAndObject(self, cloudletId, objectId, **kwargs):
        """List subscription settings for {objectId}

        Args:
            cloudletId, str: The Cloudlet Id for the User (required)

            objectId, str: Subscription Object to be returned in JSON representation (required)

            

        Returns: str
        """

        allParams = ['cloudletId', 'objectId']

        params = locals()
        for (key, val) in params['kwargs'].items():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method getSubscriptionsByCloudletAndObject" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/subscription/{cloudletId}/{objectId}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'GET'

        queryParams = {}
        headerParams = {}

        if ('cloudletId' in params):
            replacement = str(self.apiClient.toPathValue(params['cloudletId']))
            resourcePath = resourcePath.replace('{' + 'cloudletId' + '}',
                                                replacement)
        if ('objectId' in params):
            replacement = str(self.apiClient.toPathValue(params['objectId']))
            resourcePath = resourcePath.replace('{' + 'objectId' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'str')
        return responseObject
        

        

    def setSubscriptionForObject(self, cloudletId, objectId, body, **kwargs):
        """Update Subscription settings for {objectId}

        Args:
            cloudletId, str: The Cloudlet Id for the User (required)

            objectId, str: Subscription Object to be returned in JSON representation (required)

            body, Subscription: Updated Subscription info (required)

            

        Returns: str
        """

        allParams = ['cloudletId', 'objectId', 'body']

        params = locals()
        for (key, val) in params['kwargs'].items():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method setSubscriptionForObject" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/subscription/{cloudletId}/{objectId}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}

        if ('cloudletId' in params):
            replacement = str(self.apiClient.toPathValue(params['cloudletId']))
            resourcePath = resourcePath.replace('{' + 'cloudletId' + '}',
                                                replacement)
        if ('objectId' in params):
            replacement = str(self.apiClient.toPathValue(params['objectId']))
            resourcePath = resourcePath.replace('{' + 'objectId' + '}',
                                                replacement)
        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'str')
        return responseObject
        

        

    def removeSubscription(self, **kwargs):
        """??

        Args:
            

        Returns: str
        """

        allParams = []

        params = locals()
        for (key, val) in params['kwargs'].items():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method removeSubscription" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/subscription/{cloudletId}/{objectId}'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'DELETE'

        queryParams = {}
        headerParams = {}

        postData = (params['body'] if 'body' in params else None)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams)

        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'str')
        return responseObject
        

        

    




