#!/usr/bin/env python
"""
Copyright 2014 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class OPENiCloudlet:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'id': 'str',
            'location': 'str',
            'alias': 'str',
            'username': 'str',
            '_date_created': 'datetime',
            '_revision': 'str'

        }


        #Unique identifier for the Cloudlet.
        self['id'] = None # str
        #Cloudlets URI
        self['location'] = None # str
        #Human readable name for the Cloudlet.
        self['alias'] = None # str
        #Username of person who owns the Cloudlet.
        self['username'] = None # str
        #Timestamp of creation of the Cloudlet
        self['_date_created'] = None # datetime
        #Revision number associated with this version of the Cloudlet
        self['_revision'] = None # str
        
