#!/usr/bin/env python
"""
Copyright 2014 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class OPENiObject:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            '@id': 'str',
            '@location': 'str',
            '@cloudlet': 'str',
            '@type': 'str',
            '@data': 'Map',
            '_date_created': 'datetime',
            '_date_modified': 'datetime',
            '_revision': 'str'

        }


        #The Object's identifier.
        self['@id'] = None # str
        #The Object's identifier URI.
        self['@location'] = None # str
        #The Object's Cloudlet Id.
        self['@cloudlet'] = None # str
        #OPENi Type that this object is an instance of.
        self['@type'] = None # str
        #The Object's values.
        self['@data'] = None # Map
        #Date that the Type was created.
        self['_date_created'] = None # datetime
        #Date that the Type was created.
        self['_date_modified'] = None # datetime
        #Revision number associated with this version of the Object, this number must be presented when updating the object
        self['_revision'] = None # str
        
