#!/usr/bin/env python
"""
Copyright 2014 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class Subscription:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'cloudletid': 'str',
            'data': 'str',
            'type': 'str',
            'endpoint': 'str'

        }


        #The id of the Cloudlet.
        self['cloudletid'] = None # str
        #The Object/Data to watch for changes
        self['data'] = None # str
        #The Notification type. [Email, SMS, NOTIFICATION]
        self['type'] = None # str
        #Where to send the notification
        self['endpoint'] = None # str
        
